### ISSUE TITLE
Create marketplace store error

### ISSUE THREAD

**Issue by b2bviet** [icos-urenio/virtual-city-market#5]
Dear Sir,
 Please help me fix function Create marketplace store on my website at www.econgty.net,

user can not Create marketplace store, the system inform error

**Comment by dmitzias** [comment]
There is no directory entry creation code in virtual-city-market. The idea is that the directory entry is created by the administrator and a PIN is then given to a user so that he can link his account with this particular directory entry. You have removed the PIN requirement but you didn't provide the directory entry creation code.

If you want the user to be able to create his own store without a PIN you should completely remove the PIN requirement.

In templates/account/settings/register.tpl remove lines 56 to 70
In templates/account/settings/register.tpl remove line 75
In templates/account/settings/register.tpl remove lines 78 to 80
In templates/account/settings/register.tpl remove line 222
In templates/account/settings/register.tpl remove lines 238 to 249
In templates/account/settings/register.tpl remove lines 323 to 333

In templates/account/settings/business.tpl remove lines 125 to 156
In templates/account/settings/business.tpl remove lines 193 to 195
In templates/account/settings/business.tpl remove lines 478 to 496

And create the directory entry on first request by adding the following code in templates/account/settings/business.tpl before line 13.

Note: Make sure that no PIN is attached to any of your users and directory entries. First empty field "store" in "market_user" and "pin" in "directory".

```
if (!$_SESSION['User']['store']) {
    // User does not have a store.

    $error = '';

    // Create random PIN
    $i = 0;
    while ($i < 10) { // Try at most 10 times to create a unique code
        $pin = rand(1000000, 9999999);
        $sql = "SELECT * FROM market_user WHERE store='" . sqlEscape($pin) . "'";
        if (!sqlQuery($sql, $res)) {
            break; // PIN OK
        }
        $i++;
    }

    if ($pin) {
        // Create the store
        $sql = "INSERT INTO directory (id, lat, lng, pin) VALUES ('', '" . sqlEscape(GMAP_CENTER_LAT) . "', '" . sqlEscape(GMAP_CENTER_LNG) . "', '" . sqlEscape($pin) . "')";
        if ($id = sqlQuery($sql, $res)) {
            $sql = "INSERT INTO directory_ml (id, lang) VALUES ('" . sqlEscape($id) . "', '" . sqlEscape(MARKET_LANG) . "')";
            sqlQuery($sql, $res);
            $sql = "INSERT INTO directory_ps (id, creator, created, owner, role, updated, ups, gps, wps, publish) VALUES('" . $id . "', '" . $_SESSION['User']['user_id'] . "', NOW(), '" . $_SESSION['User']['user_id'] . "', '" . $_SESSION['User']['market_role_id'] . "', NOW(), '7', '2', '2', '1')";
            sqlQuery($sql, $res);

            // Update user table
            $sql = "UPDATE market_user SET store='" . sqlEscape($id) . "' WHERE user_id='" . $_SESSION['User']['user_id'] . "'";
            sqlQuery($sql, $res);

            // Reload session
            $auth =& $this->getRef('Auth');
            $sql = "SELECT * FROM market_user WHERE user_id='" . sqlEscape($_SESSION['User']['user_id']) . "'";
            $auth->userLogin($sql);

        }
        else {
            $error = __('An error occured') . '. ' . __('Please try again later.');
        }
    }
    else {
        $error = __('An error occured') . '. ' . __('Please try again later.');
    }

    if ($error) {
        // This should not happen! Halt execution.
        fatalError($error);
    }

}
```

**Comment by b2bviet** [comment]
Thank for your reply, i will try to change as you guide

**Comment by b2bviet** [comment]
May be something wrong in follow code:

$sql = "SELECT \* FROM market_user WHERE store='" . sqlEscape($pin) . "'";

at where

**Comment by dmitzias** [comment]
Don't see anything wrong. What is the problem?

**Comment by dmitzias** [comment]
When I said "empty field "store" in "market_user" and "pin" in "directory"" I meant empty like no value is stored there from previous attempts, not delete the whole field.

**Comment by b2bviet** [comment]
yes, i do not delete the field, cna you give me email address, i can send you the file i change and some info of server

**Comment by dmitzias** [comment]
There was a mistake.
Line 27 of the patch should have been:
<code>
$sql = "UPDATE market_user SET store='" . sqlEscape($id) . "' WHERE user_id='" . $_SESSION['User']['user_id'] . "'";
</code>

**Comment by b2bviet** [comment]
Thank for your help
