### ISSUE TITLE
Platform does not start

### ISSUE THREAD

**Issue by flachica** [icos-urenio/virtual-city-market#8]
Hi, I'm trying to use this code but every time I make a request I get redirected to "/en/directory/index.html" for example. Always prefixed configured language but that directory does not exist, therefore it gives me error 404. Would I could help? Thank you

**Comment by lmak** [comment]
It seems that you have a misconfigured installation. None of the urls of the platform actually exist as a physical directory on the server. You must configure correctly the mod_rewrite plugin.

My best guess is that you installed the platform in a directory different than "virtual-city-market".

If this is the case, change the root directory name in the .htaccess file. It appears two times, at lines 5 and 9.

**Comment by flachica** [comment]
I have not changed the name of the installation directory. I have everything set to "/var/www/html/virtual-city-market" and my file .htacces is the original

``` javascript
# BEGIN MARKET
<IfModule mod_rewrite.c>
SetEnv HTTP_MOD_REWRITE On
RewriteEngine On
RewriteBase /virtual-city-market/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /virtual-city-market/index.php [L]
</IfModule>
# END MARKET
```

**Comment by lmak** [comment]
I am sorry I don't know what your problem may be. So let us take it from the start.

You downloaded the code and extracted it into "/var/www/html/virtual-city-market".
You imported the "/var/www/html/virtual-city-market/data/market.sql" into a new mysql database named "virtual-city-market".
You then edited the file "/var/www/html/virtual-city-market/config.inc.php" and inserted your database password on line 12.
You then opened your browser and requested "http://servername/virtual-city-market" where servername is the name or IP of your server.
You were correctly redirected to "http://servername/virtual-city-market/en/index.html"
The browser instead of displaying the home page displays "error 404 not found".

Is this what happened?

Is there some php error in the apache log file "/var/log/httpd/error_log" ?

**Comment by patsar** [comment]
Πάνε για ύπνο Μανώλη, έχεις ταξίδι αύριο :-)
